#!/usr/bin/env python3
from sys import stdin
from base64 import b64encode
import furl
import afl
afl.init()

def main():
    url_string = stdin.read()
    parsed_url = furl.furl(url_string)

    result = {}
    result["scheme"] = parsed_url.scheme
    result["userinfo"] = parsed_url.username + (f":{parsed_url.password}" if parsed_url.password is not None else "")
    result["host"] = parsed_url.host
    result["port"] = str(parsed_url.port)
    result["path"] = str(parsed_url.path)
    result["query"] = str(parsed_url.query)
    result["fragment"] = str(parsed_url.fragment)

    print("{" + ",".join(f"\"{k}\":\"{b64encode(result[k].encode('utf-8')).decode('ascii') if result[k] is not None else ''}\"" for k, v in result.items()) + "}")

if __name__ == "__main__":
    main()
