all: analyses bench_configs runs benchmark_queue

analyses: analyses
	mkdir analyses

bench_configs: bench_configs
	mkdir bench_configs

runs: runs
	mkdir runs

benchmark_queue: benchmark_queue
	touch benchmark_queue